In [12]:
import pandas as pd

df = pd.read_csv("ecommerce_data.csv", names=["description", "category"], header= None)

print(df.shape)
df.head()

(24000, 2)

                                         description                category
0  Urban Ladder Eisner Low Back Study-Office Comp...               Household
1  Contrast living Wooden Decorative Box,Painted ...               Household
2  IO Crest SY-PCI40010 PCI RAID Host Controller ...             Electronics
3  ISAKAA Baby Socks from Just Born to 8 Years- P...  Clothing & Accessories
4  Indira Designer Women's Art Mysore Silk Saree ...  Clothing & Accessories

In [13]:
df.category.value_counts()

category
Household                 6000
Electronics               6000
Clothing & Accessories    6000
Books                     6000
Name: count, dtype: int64

In [14]:
df.dropna(inplace=True)

In [15]:
df.shape

(24000, 2)

In [19]:
df.category.replace("Clothing & Accessories", "Clothing_Accessories", inplace=True)
df.category.unique()

array(['Household', 'Electronics', 'Clothing_Accessories', 'Books'],
      dtype=object)

In [20]:
df['category'] = "__label__" + df['category'].astype(str)
df.head()

,description,category
0,Urban Ladder Eisner Low Back Study-Office Comp...,__label__Household
1,"Contrast living Wooden Decorative Box,Painted ...",__label__Household
2,IO Crest SY-PCI40010 PCI RAID Host Controller ...,__label__Electronics
3,ISAKAA Baby Socks from Just Born to 8 Years- P...,__label__Clothing_Accessories
4,Indira Designer Women's Art Mysore Silk Saree ...,__label__Clothing_Accessories

In [21]:
df['category_desc'] = "__label__" + df['description']
df.head()

,description,category,category_desc
0,Urban Ladder Eisner Low Back Study-Office Comp...,__label__Household,__label__Urban Ladder Eisner Low Back Study-Of...
1,"Contrast living Wooden Decorative Box,Painted ...",__label__Household,__label__Contrast living Wooden Decorative Box...
2,IO Crest SY-PCI40010 PCI RAID Host Controller ...,__label__Electronics,__label__IO Crest SY-PCI40010 PCI RAID Host Co...
3,ISAKAA Baby Socks from Just Born to 8 Years- P...,__label__Clothing_Accessories,__label__ISAKAA Baby Socks from Just Born to 8...
4,Indira Designer Women's Art Mysore Silk Saree ...,__label__Clothing_Accessories,__label__Indira Designer Women's Art Mysore Si...

In [23]:
df['category_desc'][1]

'__label__Contrast living Wooden Decorative Box,Painted Box, Gift Box, Jewellery Box, Wooden Box Size:- 15x15x8 cm Wooden Hand Crafted and Painted Decorative Box Specification:- * Finish- Antique * Material-Wooden Specialty: Used as Home Decor , Jewellery Box or as a Gift The beautiful and traditional hand made wooden box for home decor. The Royal Wooden Box is designed with beautiful antique finish .It is sure to add a dash of elegance to home decor . It is an ideal gift for your friends and relatives. *Limited Collection*'

In [46]:
import re

def preprocess(text): 
   text  = re.sub(r'[^\w\s]', ' ', text)
   text = re.sub(r' +', ' ', text)
   return text.strip().lower()

In [47]:
preprocess(", Wooden Box Size:- 15x15x8 cm Wooden Hand Crafted and Painted ")

'wooden box size 15x15x8 cm wooden hand crafted and painted'

In [48]:
df['category_desc'] = df['category_desc'].map(preprocess)

In [50]:
df.head(10)

,description,category,category_desc
0,Urban Ladder Eisner Low Back Study-Office Comp...,__label__Household,__label__urban ladder eisner low back study of...
1,"Contrast living Wooden Decorative Box,Painted ...",__label__Household,__label__contrast living wooden decorative box...
2,IO Crest SY-PCI40010 PCI RAID Host Controller ...,__label__Electronics,__label__io crest sy pci40010 pci raid host co...
3,ISAKAA Baby Socks from Just Born to 8 Years- P...,__label__Clothing_Accessories,__label__isakaa baby socks from just born to 8...
4,Indira Designer Women's Art Mysore Silk Saree ...,__label__Clothing_Accessories,__label__indira designer women s art mysore si...
5,Selfie: How We Became So Self-Obsessed and Wha...,__label__Books,__label__selfie how we became so self obsessed...
6,Quantum QHM8810 Keyboard with Mouse (Black) Ul...,__label__Electronics,__label__quantum qhm8810 keyboard with mouse b...
7,Y&S Uv Protected Non Polarized Wayfarer Boy's ...,__label__Clothing_Accessories,__label__y s uv protected non polarized wayfar...
8,HP external USB DVD Drive DVDRW DVD-ROM A2U56A...,__label__Electronics,__label__hp external usb dvd drive dvdrw dvd r...
9,Fujifilm Instax Mini Monochrome Film (10 Sheet...,__label__Books,__label__fujifilm instax mini monochrome film ...

In [53]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size=0.2)

In [54]:
train.shape, test.shape

((19200, 3), (4800, 3))

In [55]:
test.head()

,description,category,category_desc
2446,ITOS365 Pebbles Home Decorative Vase Fillers S...,__label__Household,__label__itos365 pebbles home decorative vase ...
571,Belkin F5L055BTBLK Laptop Cooling Pad with Pat...,__label__Electronics,__label__belkin f5l055btblk laptop cooling pad...
5515,Photron Clean Pro 6-in-1 Cleaning Kit The 6-pi...,__label__Electronics,__label__photron clean pro 6 in 1 cleaning kit...
10770,Dreams (Vintage Mini) (Vintage Minis) About th...,__label__Books,__label__dreams vintage mini vintage minis abo...
18459,Van Heusen Men's Plain Thermal Bottom Collecti...,__label__Clothing_Accessories,__label__van heusen men s plain thermal bottom...

In [56]:
train.to_csv("ecommerce.train", columns = ["category_desc"], index=False, header=False)
test.to_csv("ecommerce.test", columns=["category_desc"], index=False, header=False)

In [59]:
import fasttext

model = fasttext.train_supervised(input="ecommerce.train")
model.test("ecommerce.test")

ModuleNotFoundError: No module named 'fasttext'